In [1]:
import pandas as pd

raw_path = 'data/raw/'

geo = pd.read_csv(raw_path + "olist_geolocation_dataset.csv")

geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [2]:
geo.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [3]:
geo[['geolocation_lat', 'geolocation_lng']].describe()

       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

In [9]:
import plotly.express as px

fig = px.scatter_geo(
    geo.sample(10000),  # para no saturar
    lat='geolocation_lat',
    lon='geolocation_lng',
    hover_name='geolocation_city',
    color='geolocation_state',
    title='Geolocalización de pedidos en Brasil'
)

fig.update_layout(
    geo_scope='south america'
)

fig.show()

In [10]:
fig = px.density_mapbox(
    geo.sample(10000),
    lat='geolocation_lat',
    lon='geolocation_lng',
    radius=8,
    zoom=3,
    mapbox_style='carto-positron'
)

fig.show()

C:\Users\Brayan\AppData\Local\Temp\ipykernel_15536\3940484454.py:1: DeprecationWarning: *density_mapbox* is deprecated! Use *density_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.density_mapbox(